name: Build/Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Static Analysis
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

      - name: Build getwtxt-ng
        run: go build ./cmd/getwtxt-ng

      - name: Build adminPassGen
        run: go build ./cmd/adminPassGen

      - name: Test
        run: go test ./...